name: Webpage Scraper
#
on:
  schedule:
    # Run at 00:00 on the 1st and 15th of every month
    - cron: '0 0 1,16 * *'

    
  push:
    branches:
      - main
permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  scrape:
    runs-on: ubuntu-latest
         
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        #with:
        #  persist-credentials: true # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        #  fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.12

         
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run code1
        run: python code1.py

      - name: Check Git Status
        run: |
          git status

      - name: List data directory
        run: |
          ls -al data/
##43762575+fms-1988@users.noreply.github.com
      - name: Configure Git
        run: |
          git config --local user.name "fms-1988"
          git config --local user.email "43762575+fms-1988@users.noreply.github.com"

      #- name: Commit Changes
      #  run: |
      #    git add data/*
      #    git commit -m "GH Action Autorun $(date)"
      #  id: auto-commit-action

      - name: Commit Changes
        run: |
          git add data/*
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          else
            git commit -m "GH Action Autorun $(date)"
          fi
        id: auto-commit-action

      #- name: Send email
      #  #if: steps.auto-commit-action.outputs.changes_detected == 'true'
      #  uses: dawidd6/action-send-mail@v3
      #  with:
      #    server_address: smtp.gmail.com
      #    server_port: 465
      #    username: ${{secrets.SECRET_EMAIL}}
      #    password: ${{secrets.SECRET_EMAIL_PASSWORD}}
      #    subject: 'Stock price (target)'
      #    to: fms.morelli@gmail.com
      #    from: me
      #    html_body: file://data/alert.md
      #    convert_markdown: true
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: email-smtp.us-east-2.amazonaws.com
          server_port: 465
          username: ${{SECRETS.AWS_SES_SMTP_USER}}
          password: ${{SECRETS.AWS_SES_SMTP_PW}}
          subject: Opportunity for you
          to: fms.morelli@gmail.com
          #cc: morellicom2ls@gmail.com
          #from: alert@carbonprice.top 
          from: GitHub Campus Expert
          html_body: file://data/alert.md
          secure: true
          ignore_cert: true
          convert_markdown: true
          priority: low

      - name: Push Changes
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{secrets.SECRET_1}}#
