name: Webpage Scraper
#
on:
  schedule:
    # Runs at 08:00, Monday through Friday. 
    - cron: '0 8 * * 1-5'

    
  push:
    branches:
      - main
permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  scrape:
    runs-on: ubuntu-latest
         
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        #with:
        #  persist-credentials: true # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        #  fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.12

         
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run code1
        run: python code1.py

      - name: Check Git Status
        run: |
          git status

      - name: List data directory
        run: |
          ls -al data/
##43762575+fms-1988@users.noreply.github.com
      - name: Configure Git
        run: |
          git config --local user.name "fms-1988"
          git config --local user.email "43762575+fms-1988@users.noreply.github.com"

      #- name: Commit Changes
      #  run: |
      #    git add data/*
      #    git commit -m "GH Action Autorun $(date)"
      #  id: auto-commit-action

#      - name: Commit Changes
#        id: auto-commit-action
#        run: |
#          git add data/*
#          if git diff --cached --quiet; then
#            echo "No changes to commit"
#            echo "::set-output name=changes_detected::false"
#          else
#            echo "::set-output name=changes_detected::true"
#            git commit -m "GH Action Autorun $(date)"
#          fi

      - name: Commit Changes
        id: auto-commit-action
        run: |
          git add data/*
          if git diff --cached --quiet; then
            echo "No changes to commit"
            echo "false" > output.txt
          else
            git commit -m "GH Action Autorun $(date)"
            echo "true" > output.txt
          fi
          echo "changes_detected=$(cat output.txt)" >> $GITHUB_ENV

      - name: Send mail
        #if: steps.auto-commit-action.outputs.changes_detected == 'true'
        if: env.changes_detected == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: email-smtp.us-east-2.amazonaws.com
          server_port: 465
          username: ${{secrets.AWS_SES_SMTP_USER}}
          password: ${{secrets.AWS_SES_SMTP_PW}}
          subject: Stock Prices Alert
          to: fms.morelli@gmail.com
          from: '"User" <alert@carbonprice.top>'
          html_body: file://data/alert.html
          secure: true
          ignore_cert: true
          convert_markdown: true
          priority: low

      - name: Push Changes
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{secrets.SECRET_1}}#
